[package]
name = "nabla-python"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[lib]
name = "nabla"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[features]
extension-module = ["pyo3/extension-module"]

[dependencies]
pyo3 = "0.29"
nabla-core = { path = "../nabla-core" }
