# Type stubs for the compiled extension `quabla._quabla`.
#
# The array types and dtypes are typed in detail. The other functions and
# classes (comparison functions, the v0.1 low-level transform entry points,
# execution plans, and legacy classes) are listed with their runtime
# parameter names but loose (`Any`) types: application code reaches them
# through the v0.2 API in the pure-Python `quabla` modules. Keep this file in sync with the
# extension; tests/python/test_packaging_api.py checks that every name the
# extension exports is declared here and that every declared array method
# exists at runtime.

from collections.abc import Sequence
from typing import Any, TypeAlias, overload

__version__: str

class dtype:
    """Element type: `float32`, `float64`, or `bool_`."""

    @property
    def name(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

float32: dtype
float64: dtype
bool_: dtype
# Inside the array classes `dtype` names their property, so their
# annotations refer to the class through this alias.
_DType: TypeAlias = dtype

# Python scalars are weakly typed: they adopt the dtype of the array operand.
_Scalar: TypeAlias = bool | int | float
_Shape: TypeAlias = Sequence[int]
_Axis: TypeAlias = int | Sequence[int] | None

class Tensor:
    """An eager, immutable, C-ordered host array."""

    def __init__(self, shape: _Shape, data: Sequence[float], dtype: _DType | None = None) -> None: ...
    @property
    def shape(self) -> list[int]: ...
    @property
    def ndim(self) -> int: ...
    @property
    def dtype(self) -> _DType: ...
    @property
    def T(self) -> Tensor: ...
    def astype(self, dtype: _DType) -> Tensor: ...
    def reshape(self, *shape: int | _Shape) -> Tensor: ...
    def transpose(self, axes: _Shape | None = None) -> Tensor: ...
    def broadcast_to(self, shape: _Shape) -> Tensor: ...
    def slice(self, axis: int, start: int, length: int, step: int = 1) -> TensorView: ...
    def gather(self, indices: Any, axis: int = 0) -> Tensor: ...
    def scatter_add(self, indices: Any, updates: Tensor, axis: int = 0) -> Tensor: ...
    def item(self) -> float | bool: ...
    def tolist(self) -> Any: ...
    def to_flat_list(self) -> list[float]: ...
    def numpy(self) -> Any: ...
    def __array__(self, dtype: Any = None, copy: bool | None = None) -> Any: ...
    def __getitem__(self, key: Any) -> Tensor: ...
    def __float__(self) -> float: ...
    def __bool__(self) -> bool: ...
    # Reductions.
    def sum(self, axis: _Axis = None, keepdims: bool = False) -> Tensor: ...
    def mean(self, axis: _Axis = None, keepdims: bool = False) -> Tensor: ...
    def max(self, axis: _Axis = None, keepdims: bool = False) -> Tensor: ...
    def min(self, axis: _Axis = None, keepdims: bool = False) -> Tensor: ...
    def norm(self, axis: _Axis = None, keepdims: bool = False) -> Tensor: ...
    def all(self, axis: _Axis = None, keepdims: bool = False) -> Tensor: ...
    def any(self, axis: _Axis = None, keepdims: bool = False) -> Tensor: ...
    def cumsum(self, axis: int | None = None, reverse: bool = False) -> Tensor: ...
    # Elementwise and linear algebra.
    def abs(self) -> Tensor: ...
    def exp(self) -> Tensor: ...
    def expm1(self) -> Tensor: ...
    def log(self) -> Tensor: ...
    def log1p(self) -> Tensor: ...
    def sqrt(self) -> Tensor: ...
    def sin(self) -> Tensor: ...
    def cos(self) -> Tensor: ...
    def tanh(self) -> Tensor: ...
    def erf(self) -> Tensor: ...
    def relu(self) -> Tensor: ...
    def sigmoid(self) -> Tensor: ...
    def softplus(self) -> Tensor: ...
    def isnan(self) -> Tensor: ...
    def isfinite(self) -> Tensor: ...
    def logical_not(self) -> Tensor: ...
    def stop_gradient(self) -> Tensor: ...
    def powi(self, exponent: int) -> Tensor: ...
    def atan2(self, x: Tensor | _Scalar) -> Tensor: ...
    def tril(self) -> Tensor: ...
    def triu(self) -> Tensor: ...
    def cholesky(self) -> Tensor: ...
    def solve(self, rhs: Tensor) -> Tensor: ...
    def solve_triangular(self, rhs: Tensor, lower: bool = True, transpose: bool = False) -> Tensor: ...
    def add(self, rhs: Tensor | _Scalar) -> Tensor: ...
    def sub(self, rhs: Tensor | _Scalar) -> Tensor: ...
    def mul(self, rhs: Tensor | _Scalar) -> Tensor: ...
    def div(self, rhs: Tensor | _Scalar) -> Tensor: ...
    def matmul(self, rhs: Tensor) -> Tensor: ...
    def maximum(self, rhs: Tensor | _Scalar) -> Tensor: ...
    def minimum(self, rhs: Tensor | _Scalar) -> Tensor: ...
    def equal(self, rhs: Tensor | _Scalar) -> Tensor: ...
    def not_equal(self, rhs: Tensor | _Scalar) -> Tensor: ...
    def greater(self, rhs: Tensor | _Scalar) -> Tensor: ...
    def greater_equal(self, rhs: Tensor | _Scalar) -> Tensor: ...
    def gt(self, rhs: Tensor | _Scalar) -> Tensor: ...
    def less(self, rhs: Tensor | _Scalar) -> Tensor: ...
    def less_equal(self, rhs: Tensor | _Scalar) -> Tensor: ...
    def logical_and(self, rhs: Tensor | _Scalar) -> Tensor: ...
    def logical_or(self, rhs: Tensor | _Scalar) -> Tensor: ...
    # Operators. A traced operand makes the result traced.
    @overload
    def __add__(self, value: TraceTensor) -> TraceTensor: ...
    @overload
    def __add__(self, value: Tensor | _Scalar) -> Tensor: ...
    def __radd__(self, value: _Scalar) -> Tensor: ...
    @overload
    def __sub__(self, value: TraceTensor) -> TraceTensor: ...
    @overload
    def __sub__(self, value: Tensor | _Scalar) -> Tensor: ...
    def __rsub__(self, value: _Scalar) -> Tensor: ...
    @overload
    def __mul__(self, value: TraceTensor) -> TraceTensor: ...
    @overload
    def __mul__(self, value: Tensor | _Scalar) -> Tensor: ...
    def __rmul__(self, value: _Scalar) -> Tensor: ...
    @overload
    def __truediv__(self, value: TraceTensor) -> TraceTensor: ...
    @overload
    def __truediv__(self, value: Tensor | _Scalar) -> Tensor: ...
    def __rtruediv__(self, value: _Scalar) -> Tensor: ...
    @overload
    def __pow__(self, value: TraceTensor, mod: None = None) -> TraceTensor: ...
    @overload
    def __pow__(self, value: Tensor | _Scalar, mod: None = None) -> Tensor: ...
    def __rpow__(self, value: _Scalar, mod: None = None) -> Tensor: ...
    @overload
    def __matmul__(self, value: TraceTensor) -> TraceTensor: ...
    @overload
    def __matmul__(self, value: Tensor) -> Tensor: ...
    def __rmatmul__(self, value: Tensor) -> Tensor: ...
    def __neg__(self) -> Tensor: ...
    def __invert__(self) -> Tensor: ...
    def __and__(self, value: Tensor | _Scalar) -> Tensor: ...
    def __rand__(self, value: _Scalar) -> Tensor: ...
    def __or__(self, value: Tensor | _Scalar) -> Tensor: ...
    def __ror__(self, value: _Scalar) -> Tensor: ...
    # Comparisons are elementwise and return bool tensors.
    def __eq__(self, value: object) -> Tensor: ...  # type: ignore[override]
    def __ne__(self, value: object) -> Tensor: ...  # type: ignore[override]
    def __lt__(self, value: Tensor | _Scalar) -> Tensor: ...
    def __le__(self, value: Tensor | _Scalar) -> Tensor: ...
    def __gt__(self, value: Tensor | _Scalar) -> Tensor: ...
    def __ge__(self, value: Tensor | _Scalar) -> Tensor: ...
    def __hash__(self) -> int: ...
    # Constructors (the `quabla.zeros`, `quabla.arange`, ... functions wrap
    # these and add dtype handling).
    @staticmethod
    def zeros(shape: _Shape) -> Tensor: ...
    @staticmethod
    def ones(shape: _Shape) -> Tensor: ...
    @staticmethod
    def full(shape: _Shape, value: float) -> Tensor: ...
    @staticmethod
    def eye(rows: int, cols: int | None = None) -> Tensor: ...
    @staticmethod
    def arange(start: float, stop: float, step: float = 1.0) -> Tensor: ...
    @staticmethod
    def linspace(start: float, stop: float, num: int) -> Tensor: ...
    @staticmethod
    def random_normal(shape: _Shape, key: int, mean: float = 0.0, stddev: float = 1.0) -> Tensor: ...
    @staticmethod
    def random_uniform(
        shape: _Shape, key: int, minval: float = 0.0, maxval: float = 1.0, dtype: _DType | None = None
    ) -> Tensor: ...
    @staticmethod
    def glorot_normal(shape: _Shape, key: int) -> Tensor: ...
    @staticmethod
    def split_key(key: int, count: int) -> list[int]: ...
    @staticmethod
    def fold_in_key(key: int, data: int) -> int: ...

class TensorView:
    """A zero-copy, read-only strided view of a `Tensor`."""

    @property
    def shape(self) -> list[int]: ...
    @property
    def ndim(self) -> int: ...
    @property
    def strides(self) -> list[int]: ...
    @property
    def offset(self) -> int: ...
    def slice(self, axis: int, start: int, length: int, step: int = 1) -> TensorView: ...
    def to_flat_list(self) -> list[float]: ...
    def to_tensor(self) -> Tensor: ...

class TraceTensor:
    """A symbolic array inside a traced function (`quabla.jit`,
    `quabla.grad`, ...): it has a shape and dtype but no values."""

    @property
    def shape(self) -> list[int]: ...
    @property
    def dtype(self) -> _DType: ...
    @property
    def node_id(self) -> int: ...
    @property
    def T(self) -> TraceTensor: ...
    def astype(self, dtype: _DType) -> TraceTensor: ...
    def reshape(self, *shape: int | _Shape) -> TraceTensor: ...
    def transpose(self, axes: _Shape | None = None) -> TraceTensor: ...
    def broadcast_to(self, shape: _Shape) -> TraceTensor: ...
    def slice(self, axis: int, start: int, stop: int) -> TraceTensor: ...
    def gather(self, indices: Any, axis: int = 0) -> TraceTensor: ...
    def scatter_add(self, indices: Any, updates: Any, axis: int = 0) -> TraceTensor: ...
    def where_select(self, on_true: Any, on_false: Any) -> TraceTensor: ...
    def __getitem__(self, key: Any) -> TraceTensor: ...
    def sum(self, axis: _Axis = None, keepdims: bool = False) -> TraceTensor: ...
    def mean(self, axis: _Axis = None, keepdims: bool = False) -> TraceTensor: ...
    def max(self, axis: _Axis = None, keepdims: bool = False) -> TraceTensor: ...
    def min(self, axis: _Axis = None, keepdims: bool = False) -> TraceTensor: ...
    def norm(self, axis: _Axis = None, keepdims: bool = False) -> TraceTensor: ...
    def all(self, axis: _Axis = None, keepdims: bool = False) -> TraceTensor: ...
    def any(self, axis: _Axis = None, keepdims: bool = False) -> TraceTensor: ...
    def cumsum(self, axis: int | None = None, reverse: bool = False) -> TraceTensor: ...
    def abs(self) -> TraceTensor: ...
    def exp(self) -> TraceTensor: ...
    def expm1(self) -> TraceTensor: ...
    def log(self) -> TraceTensor: ...
    def log1p(self) -> TraceTensor: ...
    def sqrt(self) -> TraceTensor: ...
    def sin(self) -> TraceTensor: ...
    def cos(self) -> TraceTensor: ...
    def tanh(self) -> TraceTensor: ...
    def erf(self) -> TraceTensor: ...
    def relu(self) -> TraceTensor: ...
    def sigmoid(self) -> TraceTensor: ...
    def softplus(self) -> TraceTensor: ...
    def isnan(self) -> TraceTensor: ...
    def isfinite(self) -> TraceTensor: ...
    def logical_not(self) -> TraceTensor: ...
    def stop_gradient(self) -> TraceTensor: ...
    def powi(self, exponent: int) -> TraceTensor: ...
    def atan2(self, x: Any) -> TraceTensor: ...
    def tril(self) -> TraceTensor: ...
    def triu(self) -> TraceTensor: ...
    def cholesky(self) -> TraceTensor: ...
    def solve(self, rhs: Any) -> TraceTensor: ...
    def solve_triangular(self, rhs: Any, lower: bool = True, transpose: bool = False) -> TraceTensor: ...
    def add(self, rhs: Any) -> TraceTensor: ...
    def sub(self, rhs: Any) -> TraceTensor: ...
    def mul(self, rhs: Any) -> TraceTensor: ...
    def div(self, rhs: Any) -> TraceTensor: ...
    def matmul(self, rhs: Any) -> TraceTensor: ...
    def maximum(self, rhs: Any) -> TraceTensor: ...
    def minimum(self, rhs: Any) -> TraceTensor: ...
    def equal(self, rhs: Any) -> TraceTensor: ...
    def not_equal(self, rhs: Any) -> TraceTensor: ...
    def greater(self, rhs: Any) -> TraceTensor: ...
    def greater_equal(self, rhs: Any) -> TraceTensor: ...
    def gt(self, rhs: Any) -> TraceTensor: ...
    def less(self, rhs: Any) -> TraceTensor: ...
    def less_equal(self, rhs: Any) -> TraceTensor: ...
    def logical_and(self, rhs: Any) -> TraceTensor: ...
    def logical_or(self, rhs: Any) -> TraceTensor: ...
    def __add__(self, value: Tensor | TraceTensor | _Scalar) -> TraceTensor: ...
    def __radd__(self, value: Tensor | _Scalar) -> TraceTensor: ...
    def __sub__(self, value: Tensor | TraceTensor | _Scalar) -> TraceTensor: ...
    def __rsub__(self, value: Tensor | _Scalar) -> TraceTensor: ...
    def __mul__(self, value: Tensor | TraceTensor | _Scalar) -> TraceTensor: ...
    def __rmul__(self, value: Tensor | _Scalar) -> TraceTensor: ...
    def __truediv__(self, value: Tensor | TraceTensor | _Scalar) -> TraceTensor: ...
    def __rtruediv__(self, value: Tensor | _Scalar) -> TraceTensor: ...
    def __pow__(self, value: Tensor | TraceTensor | _Scalar, mod: None = None) -> TraceTensor: ...
    def __rpow__(self, value: Tensor | _Scalar, mod: None = None) -> TraceTensor: ...
    def __matmul__(self, value: Tensor | TraceTensor) -> TraceTensor: ...
    def __rmatmul__(self, value: Tensor) -> TraceTensor: ...
    def __neg__(self) -> TraceTensor: ...
    def __invert__(self) -> TraceTensor: ...
    def __and__(self, value: Tensor | TraceTensor | _Scalar) -> TraceTensor: ...
    def __rand__(self, value: Tensor | _Scalar) -> TraceTensor: ...
    def __or__(self, value: Tensor | TraceTensor | _Scalar) -> TraceTensor: ...
    def __ror__(self, value: Tensor | _Scalar) -> TraceTensor: ...
    def __eq__(self, value: object) -> TraceTensor: ...  # type: ignore[override]
    def __ne__(self, value: object) -> TraceTensor: ...  # type: ignore[override]
    def __lt__(self, value: Tensor | TraceTensor | _Scalar) -> TraceTensor: ...
    def __le__(self, value: Tensor | TraceTensor | _Scalar) -> TraceTensor: ...
    def __gt__(self, value: Tensor | TraceTensor | _Scalar) -> TraceTensor: ...
    def __ge__(self, value: Tensor | TraceTensor | _Scalar) -> TraceTensor: ...
    def __hash__(self) -> int: ...
    def compile_cpu(self) -> Any: ...
    def compile_cuda(self, device_ordinal: int = 0) -> Any: ...
    def compile_mlx(self) -> Any: ...
    def symbolic_jvp(self, input_name: str) -> Any: ...
    def symbolic_vjp(self, cotangent_name: str) -> Any: ...

# Module-level elementwise functions; a traced operand makes the result
# traced.
@overload
def where(mask: Tensor, on_true: Tensor | _Scalar, on_false: Tensor | _Scalar) -> Tensor: ...
@overload
def where(mask: Any, on_true: Any, on_false: Any) -> Any: ...
@overload
def stack(tensors: Sequence[Tensor], axis: int = 0) -> Tensor: ...
@overload
def stack(tensors: Sequence[Any], axis: int = 0) -> Any: ...
@overload
def concat(matrices: Sequence[Tensor], axis: int) -> Tensor: ...
@overload
def concat(matrices: Sequence[Any], axis: int) -> Any: ...
def einsum(equation: str, operands: Sequence[Any]) -> Any: ...
def greater(lhs: Any, rhs: Any) -> Any: ...
def greater_equal(lhs: Any, rhs: Any) -> Any: ...
def less(lhs: Any, rhs: Any) -> Any: ...
def less_equal(lhs: Any, rhs: Any) -> Any: ...
def equal(lhs: Any, rhs: Any) -> Any: ...
def not_equal(lhs: Any, rhs: Any) -> Any: ...
def logical_and(lhs: Any, rhs: Any) -> Any: ...
def logical_or(lhs: Any, rhs: Any) -> Any: ...
def logical_not(value: Any) -> Any: ...
def isnan(value: Any) -> Any: ...
def isfinite(value: Any) -> Any: ...

# Opaque classes: compiled programs, execution plans, transform objects, and
# the v0.1 `Matrix` API.
class Compiler:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
class Program:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
class Executable:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
class Matrix:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
class Adam:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
class TensorTraceGraph:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
class TensorTraceResult:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
class TensorCpuExecutionPlan:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
class TensorCudaExecutionPlan:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
class TensorMlxExecutionPlan:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
class TensorCudaAdamOptimizer:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
class TensorMlxAdamOptimizer:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
class TensorGradScalarFunction:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
class TensorValueAndGradFunction:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
class TensorHessianScalarFunction:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
class TensorHvpScalarFunction:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
class TensorJitFunction:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
class TensorCondFunction:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
class TensorCondJvpFunction:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
class TensorCondValueAndGradFunction:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
class TensorBatchJitFunction:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
class TensorBatchValueAndGradFunction:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
class TensorBatchMlxValueAndGradFunction:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
class TensorBatchCudaJitFunction:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
class TensorBatchCudaValueAndGradFunction:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
class TensorCudaValueAndGradFunction:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
class TensorMlxValueAndGradFunction:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
class TensorVjpFunction:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
class TensorJvpFunction:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
class TensorJacobianFunction:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
class TraceGraph:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
class TraceMatrix:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
class TraceResult:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
class CpuExecutionPlan:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
class GradFunction:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
class GradScalarFunction:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
class GradScalarTransform:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
class ValueAndGradFunction:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
class VjpFunction:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
class JacobianFunction:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
class JacobiansFunction:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
class JvpFunction:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
class JitFunction:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
class JitTransform:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
class TensorVmapFunction:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
class TensorVmapHvpScalarFunction:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
class TensorVmapCudaFunction:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
class TensorVmapCudaHvpScalarFunction:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
class TensorVmapCudaJvpFunction:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
class TensorVmapMlxFunction:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
class TensorVmapMlxJvpFunction:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
class TensorVmapMlxVjpFunction:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
class TensorVmapVjpFunction:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
class TensorVmapJvpFunction:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
class TensorVmapCudaVjpFunction:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

# v0.1 transform entry points and device-specific builders.
def sum_gradients(gradient_sets: Any, parameter_names: Any = None) -> Any: ...
def trace(function: Any, input_specs: Any) -> Any: ...
def grad(function: Any, input_specs: Any, values: Any, output_cotangent: Any) -> Any: ...
def grad_fn(function: Any, input_specs: Any, output_cotangent: Any) -> Any: ...
def grad_scalar_fn(function: Any, input_specs: Any) -> Any: ...
def value_and_grad_fn(function: Any, input_specs: Any, output_cotangent: Any) -> Any: ...
def vjp_fn(function: Any, input_specs: Any) -> Any: ...
def jacobian_fn(function: Any, input_specs: Any) -> Any: ...
def jacobians_fn(function: Any, input_specs: Any) -> Any: ...
def jvp_fn(function: Any, input_specs: Any) -> Any: ...
def grad_scalar(input_specs: Any) -> Any: ...
def jit(input_specs: Any) -> Any: ...
def trace_tensor(function: Any, input_specs: Any) -> Any: ...
def tensor_grad_scalar_fn(function: Any, input_specs: Any) -> Any: ...
def tensor_value_and_grad_fn(function: Any, input_specs: Any) -> Any: ...
def tensor_hessian_scalar_fn(function: Any, input_specs: Any, input_name: Any) -> Any: ...
def tensor_hvp_scalar_fn(function: Any, input_specs: Any, input_name: Any) -> Any: ...
def tensor_jit_fn(function: Any, input_specs: Any) -> Any: ...
def tensor_cond(predicate: Any, on_true: Any, on_false: Any, operands: Any) -> Any: ...
def tensor_cond_fn(on_true: Any, on_false: Any, input_specs: Any) -> Any: ...
def tensor_cond_jvp_fn(on_true: Any, on_false: Any, input_specs: Any) -> Any: ...
def tensor_cond_value_and_grad_fn(on_true: Any, on_false: Any, input_specs: Any) -> Any: ...
def tensor_jit_batch_fn(function: Any, input_names: Any, in_axes: Any = None, batch_axis: Any = 0, max_specializations: Any = 4) -> Any: ...
def tensor_jit_batch_cuda_fn(function: Any, input_names: Any, in_axes: Any = None, batch_axis: Any = 0, max_specializations: Any = 4, device_ordinal: Any = 0) -> Any: ...
def tensor_value_and_grad_batch_fn(function: Any, input_names: Any, in_axes: Any = None, batch_axis: Any = 0, max_specializations: Any = 4) -> Any: ...
def tensor_value_and_grad_batch_cuda_fn(function: Any, input_names: Any, parameter_names: Any, in_axes: Any = None, batch_axis: Any = 0, max_specializations: Any = 4, device_ordinal: Any = 0) -> Any: ...
def tensor_value_and_grad_batch_mlx_fn(function: Any, input_names: Any, parameter_names: Any, in_axes: Any = None, batch_axis: Any = 0, max_specializations: Any = 4) -> Any: ...
def tensor_fori_loop(lower: Any, upper: Any, body: Any, init: Any) -> Any: ...
def tensor_fori_loop_region(lower: Any, upper: Any, body: Any, init: Any, operands: Any) -> Any: ...
def tensor_scan_region(lower: Any, upper: Any, body: Any, init: Any, operands: Any) -> Any: ...
def tensor_scan(length: Any, body: Any, init: Any) -> Any: ...
def tensor_vmap_fn(function: Any, input_specs: Any, batch_size: Any, in_axes: Any = None, out_axis: Any = 0) -> Any: ...
def tensor_jit_cuda_fn(function: Any, input_specs: Any, device_ordinal: Any = 0) -> Any: ...
def tensor_value_and_grad_cuda_fn(function: Any, input_specs: Any, parameter_names: Any, device_ordinal: Any = 0) -> Any: ...
def tensor_value_and_grad_data_parallel_cuda_fn(function: Any, input_specs: Any, parameter_names: Any, mapped_input_names: Any, device_ordinals: Any, reduction: Any = "mean") -> Any: ...
def tensor_value_and_grad_mlx_fn(function: Any, input_specs: Any, parameter_names: Any) -> Any: ...
def mlx_adam_loss_optimizer(loss: Any, parameter_names: Any, inputs: Any, learning_rate: Any, retained_input_names: Any = None, beta1: Any = 0.9, beta2: Any = 0.999, epsilon: Any = 1e-08) -> Any: ...
def tensor_vmap_cuda_fn(function: Any, input_specs: Any, batch_size: Any, in_axes: Any = None, out_axis: Any = 0, device_ordinal: Any = 0) -> Any: ...
def tensor_vmap_mlx_fn(function: Any, input_specs: Any, batch_size: Any, in_axes: Any = None, out_axis: Any = 0) -> Any: ...
def tensor_vmap_vjp_fn(function: Any, input_specs: Any, batch_size: Any, in_axes: Any = None, out_axis: Any = 0) -> Any: ...
def tensor_vmap_vjp_mlx_fn(function: Any, input_specs: Any, batch_size: Any, in_axes: Any = None, out_axis: Any = 0) -> Any: ...
def tensor_vmap_vjp_cuda_fn(function: Any, input_specs: Any, batch_size: Any, in_axes: Any = None, out_axis: Any = 0, device_ordinal: Any = 0) -> Any: ...
def tensor_vmap_jvp_fn(function: Any, input_specs: Any, batch_size: Any, in_axes: Any = None, out_axis: Any = 0) -> Any: ...
def tensor_vmap_jvp_mlx_fn(function: Any, input_specs: Any, batch_size: Any, in_axes: Any = None, out_axis: Any = 0) -> Any: ...
def tensor_vmap_jvp_cuda_fn(function: Any, input_specs: Any, batch_size: Any, in_axes: Any = None, out_axis: Any = 0, device_ordinal: Any = 0) -> Any: ...
def tensor_vmap_hvp_scalar_fn(function: Any, input_specs: Any, batch_size: Any, input_name: Any, in_axes: Any = None, out_axis: Any = 0) -> Any: ...
def tensor_vmap_hvp_scalar_cuda_fn(function: Any, input_specs: Any, batch_size: Any, input_name: Any, in_axes: Any = None, out_axis: Any = 0, device_ordinal: Any = 0) -> Any: ...
def tensor_vjp_fn(function: Any, input_specs: Any) -> Any: ...
def tensor_jvp_fn(function: Any, input_specs: Any) -> Any: ...
def tensor_jacobian_fn(function: Any, input_specs: Any, input_name: Any) -> Any: ...
def cuda_adam_step(plans: Any, inputs: Any, learning_rate: Any, retained_input_names: Any = None, beta1: Any = 0.9, beta2: Any = 0.999, epsilon: Any = 1e-08) -> Any: ...
def cuda_adam_optimizer(plans: Any, inputs: Any, learning_rate: Any, retained_input_names: Any = None, beta1: Any = 0.9, beta2: Any = 0.999, epsilon: Any = 1e-08) -> Any: ...
def cuda_adam_vjp_optimizer(gradients: Any, inputs: Any, learning_rate: Any, retained_input_names: Any = None, beta1: Any = 0.9, beta2: Any = 0.999, epsilon: Any = 1e-08, device_ordinal: Any = 0) -> Any: ...
def cuda_adam_loss_optimizer(loss: Any, parameter_names: Any, inputs: Any, learning_rate: Any, retained_input_names: Any = None, beta1: Any = 0.9, beta2: Any = 0.999, epsilon: Any = 1e-08, device_ordinal: Any = 0) -> Any: ...

__all__ = [
    "Compiler",
    "Program",
    "Executable",
    "Matrix",
    "Adam",
    "sum_gradients",
    "dtype",
    "float32",
    "float64",
    "bool_",
    "greater",
    "greater_equal",
    "less",
    "less_equal",
    "equal",
    "not_equal",
    "logical_and",
    "logical_or",
    "logical_not",
    "isnan",
    "isfinite",
    "Tensor",
    "TensorView",
    "TensorTraceGraph",
    "TraceTensor",
    "TensorTraceResult",
    "TensorCpuExecutionPlan",
    "TensorCudaExecutionPlan",
    "TensorMlxExecutionPlan",
    "TensorCudaAdamOptimizer",
    "TensorMlxAdamOptimizer",
    "TensorGradScalarFunction",
    "TensorValueAndGradFunction",
    "TensorHessianScalarFunction",
    "TensorHvpScalarFunction",
    "TensorJitFunction",
    "TensorCondFunction",
    "TensorCondJvpFunction",
    "TensorCondValueAndGradFunction",
    "TensorBatchJitFunction",
    "TensorBatchValueAndGradFunction",
    "TensorBatchMlxValueAndGradFunction",
    "TensorBatchCudaJitFunction",
    "TensorBatchCudaValueAndGradFunction",
    "TensorCudaValueAndGradFunction",
    "TensorMlxValueAndGradFunction",
    "TensorVjpFunction",
    "TensorJvpFunction",
    "TensorJacobianFunction",
    "TraceGraph",
    "TraceMatrix",
    "TraceResult",
    "CpuExecutionPlan",
    "GradFunction",
    "GradScalarFunction",
    "GradScalarTransform",
    "ValueAndGradFunction",
    "VjpFunction",
    "JacobianFunction",
    "JacobiansFunction",
    "JvpFunction",
    "JitFunction",
    "JitTransform",
    "trace",
    "grad",
    "grad_fn",
    "grad_scalar_fn",
    "value_and_grad_fn",
    "vjp_fn",
    "jacobian_fn",
    "jacobians_fn",
    "jvp_fn",
    "grad_scalar",
    "jit",
    "trace_tensor",
    "tensor_grad_scalar_fn",
    "tensor_value_and_grad_fn",
    "tensor_hessian_scalar_fn",
    "tensor_hvp_scalar_fn",
    "tensor_jit_fn",
    "tensor_cond",
    "tensor_cond_fn",
    "tensor_cond_jvp_fn",
    "tensor_cond_value_and_grad_fn",
    "tensor_jit_batch_fn",
    "tensor_jit_batch_cuda_fn",
    "tensor_value_and_grad_batch_fn",
    "tensor_value_and_grad_batch_cuda_fn",
    "tensor_value_and_grad_batch_mlx_fn",
    "tensor_fori_loop",
    "tensor_fori_loop_region",
    "tensor_scan_region",
    "tensor_scan",
    "TensorVmapFunction",
    "TensorVmapHvpScalarFunction",
    "TensorVmapCudaFunction",
    "TensorVmapCudaHvpScalarFunction",
    "TensorVmapCudaJvpFunction",
    "TensorVmapMlxFunction",
    "TensorVmapMlxJvpFunction",
    "TensorVmapMlxVjpFunction",
    "TensorVmapVjpFunction",
    "TensorVmapJvpFunction",
    "TensorVmapCudaVjpFunction",
    "tensor_vmap_fn",
    "tensor_jit_cuda_fn",
    "tensor_value_and_grad_cuda_fn",
    "tensor_value_and_grad_data_parallel_cuda_fn",
    "tensor_value_and_grad_mlx_fn",
    "mlx_adam_loss_optimizer",
    "tensor_vmap_cuda_fn",
    "tensor_vmap_mlx_fn",
    "tensor_vmap_vjp_fn",
    "tensor_vmap_vjp_mlx_fn",
    "tensor_vmap_vjp_cuda_fn",
    "tensor_vmap_jvp_fn",
    "tensor_vmap_jvp_mlx_fn",
    "tensor_vmap_jvp_cuda_fn",
    "tensor_vmap_hvp_scalar_fn",
    "tensor_vmap_hvp_scalar_cuda_fn",
    "tensor_vjp_fn",
    "tensor_jvp_fn",
    "tensor_jacobian_fn",
    "cuda_adam_step",
    "cuda_adam_optimizer",
    "cuda_adam_vjp_optimizer",
    "cuda_adam_loss_optimizer",
    "where",
    "concat",
    "stack",
    "einsum",
]
